---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Application Tests
description: Takes an app, container image and token then runs container tests

inputs:
  app:
    description: Application Name
    required: true
  image:
    description: Image
    required: true
  token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Actions Script Path
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: | # zizmor: ignore[github-env]
        echo "${GITHUB_ACTION_PATH}" >> $GITHUB_PATH

    - name: Setup Testing Tools
      shell: bash
      env:
        APP: ${{ inputs.app }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        setup.sh "${APP}"

    - name: Run Tests
      shell: bash
      env:
        APP: ${{ inputs.app }}
        IMAGE: ${{ inputs.image }}
      run: |
        run.sh "${APP}" "${IMAGE}"
