---
area/apps:
  - changed-files:
      - any-glob-to-any-file:
          - apps/**/*
          - include/**/*
area/github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - .renovate/**/*
          - .renovaterc.json5
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - .taskfiles/**/*
          - Taskfile.yaml
